
DROP DATABASE IF EXISTS MUSIC_STUDIO;
CREATE DATABASE IF NOT EXISTS MUSIC_STUDIO;
USE MUSIC_STUDIO;

DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE IF NOT EXISTS EMPLOYEE(
EMP_ID INT AUTO_INCREMENT PRIMARY KEY,
EMP_FIRST_NAME VARCHAR(50) NOT NULL,
EMP_LAST_NAME VARCHAR(50) NOT NULL,
EMP_EMAIL VARCHAR(50)
);

DROP TABLE IF EXISTS CLIENT;

CREATE TABLE IF NOT EXISTS CLIENT(
CLIENT_FIRST_NAME VARCHAR(50) NOT NULL,
CLIENT_LAST_NAME VARCHAR(50) NOT NULL,
CLIENT_EMAIL VARCHAR(100) PRIMARY KEY NOT NULL,
ADDRESS VARCHAR(100),
PHONE_NUMBER VARCHAR(20)
);

DROP TABLE IF EXISTS SERVICES; 

CREATE TABLE IF NOT EXISTS SERVICES(
SERVICE_NAME VARCHAR(50) PRIMARY KEY NOT NULL,
SERVICE_DESCRIPTION VARCHAR(300),
PRICE FLOAT
);

DROP TABLE IF EXISTS BOOKING;

-- JOIN TABLE WHICH TRACKS CLIENT BOOKING
CREATE TABLE IF NOT EXISTS BOOKING(
BOOKING_NUMBER INT AUTO_INCREMENT PRIMARY KEY,
CLIENT_EMAIL VARCHAR(100),
SERVICE_NAME VARCHAR(50),
EMP_ID INT,
BOOKING_DATE DATE NOT NULL,
FOREIGN KEY(EMP_ID) REFERENCES EMPLOYEE(EMP_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(CLIENT_EMAIL) REFERENCES CLIENT(CLIENT_EMAIL) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(SERVICE_NAME) REFERENCES SERVICES(SERVICE_NAME) ON DELETE CASCADE ON UPDATE CASCADE
);
