SELECT * FROM BOOKING;
SELECT * FROM SERVICES;
SELECT * FROM EMPLOYEE;
SELECT * FROM CLIENT;

SELECT SUM(SERVICES.PRICE)
FROM SERVICES
JOIN BOOKING ON BOOKING.SERVICE_NAME = SERVICES.SERVICE_NAME
WHERE BOOKING_DATE LIKE '_____03%';

SELECT calc_month_earnings('04');

SELECT SUM(SERVICES.PRICE)
FROM BOOKING
JOIN SERVICES ON SERVICES.SERVICE_NAME = BOOKING.SERVICE_NAME
JOIN EMPLOYEE ON EMPLOYEE.EMP_ID = BOOKING.EMP_ID
WHERE BOOKING.EMP_ID = 5;

SELECT calc_emp_earnings(5);

SELECT BOOKING.BOOKING_NUMBER, BOOKING.CLIENT_EMAIL, BOOKING.EMP_ID, SUM(SERVICES.PRICE) AS EARNINGS
	FROM BOOKING
	JOIN SERVICES ON SERVICES.SERVICE_NAME = BOOKING.SERVICE_NAME
	JOIN EMPLOYEE ON EMPLOYEE.EMP_ID = BOOKING.EMP_ID
	WHERE BOOKING.EMP_ID = 1
    GROUP BY BOOKING.BOOKING_NUMBER;
    
CALL emp_earnings(3);
CALL year_earnings('2024');
CALL month_earnings('02');
CALL displayEmployees();
CALL client_sessions('j@z.com');


SELECT SUM(SERVICES.PRICE) AS EARNINGS
FROM SERVICES
JOIN BOOKING ON BOOKING.SERVICE_NAME = SERVICES.SERVICE_NAME
WHERE BOOKING_DATE LIKE '2024%';
